- id: mypy
  name: mypy
  description: run mypy from your environment, properly detecting imports and types
  entry: pre-commit-mypy-wrapper
  language: python
  types_or: [python, pyi]
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: '2.9.2'
